### ISSUE TITLE
FR1. Account Creation 

### ISSUE THREAD

**Issue by yellow-tulips** [WSU-4110/mental-health-helper#10]
|FR1. Account Creation |
|---|
|**Goal**: The user will have the ability to create an account.
**Stakeholders:** Customers and Users|
| **Description:** New users can open a new account when first visiting the website by choosing the “create account” option. After clicking this option, they will need to choose a username and password and click “ok”.  |
| **Origin:** The group has decided this during their second meeting on February 1st, 2023. |
| **Version:** 1.0  |
|**Date:** 2/1/2023
|  **Priority:** 1 |

**Comment by joerossi215** [comment]
completed
