### ISSUE TITLE
FR2. Login

### ISSUE THREAD

**Issue by yellow-tulips** [WSU-4110/mental-health-helper#11]
|FR2. Login |
|---|
|**Goal**: The user's successful login to their account is the main objective of the login process.
**Stakeholders:** Customers and Users|
| **Description:** A set of login credentials is used to verify a user. These include a username and password. After entering their username and password, the user will click the login button and be directed to their home page.  |
| **Origin:** Team members decided on this during the first meeting, when first discussing the project. |
| **Version:** 1.0  |
|**Date:** 1/31/2023
|  **Priority:** 2 |

**Comment by joerossi215** [comment]
completed
