### ISSUE TITLE
FR3. Logout

### ISSUE THREAD

**Issue by yellow-tulips** [WSU-4110/mental-health-helper#12]
|FR3. Logout |
|---|
|**Goal**: The user will be able to logout.
**Stakeholders:** Customers and Users|
| **Description:** By logging out, you can stop other users from entering your account from the same computer without first confirming their identity. It is crucial to secure your account since it aids in preventing illegal acts during the current login session or protecting the access of the current user. There will be a button that allows the user to logout. |
| **Origin:** Team members decided on this during the first meeting, when first discussing the project. |
| **Version:** 1.0  |
|**Date:** 1/31/2023
|  **Priority:** 3 |

**Comment by joerossi215** [comment]
user can log out
