### ISSUE TITLE
FR4. Find Doctor Info

### ISSUE THREAD

**Issue by yellow-tulips** [WSU-4110/mental-health-helper#13]
|FR4. Find Doctor Info |
|---|
|**Goal**: The user will be able to look at each Doctors Information
**Stakeholders:** Customers and Users|
| **Description:** The system will have a list of available doctors with information for each. The user will have the option to email doctor. It will forward them to their primary email application, allowing the user to easily send their questions to the doctor. |
| **Origin:** The group has decided this during their first meeting on January 30th, 2023 |
| **Version:** 1.0  |
|**Date:** 1/31/2023
|  **Priority:** 4 |

**Comment by joerossi215** [comment]
completed
