### ISSUE TITLE
FR5. Add Post 

### ISSUE THREAD

**Issue by yellow-tulips** [WSU-4110/mental-health-helper#14]
|FR5. Add Post |
|---|
|**Goal**: The user will be able to post in the interaction page
**Stakeholders:** Customers and Users|
| **Description:** There will be an icon where the user can click, and it will allow them to write a post. They can post their thoughts on the page. They can also post about what they’re going through, and other users can respond to them. |
| **Origin:** Based on the project’s features, team members came up with the description during the first meeting |
| **Version:** 1.0  |
|**Date:** 1/31/2023
|  **Priority:** 5 |

**Comment by joerossi215** [comment]
completed
