### ISSUE TITLE
FR7. Submit Form to Contact Us

### ISSUE THREAD

**Issue by yellow-tulips** [WSU-4110/mental-health-helper#15]
|FR7. Submit Form to Contact Us |
|---|
|**Goal**: The user will be able to contact us, the developers of the website, if they have any questions.
**Stakeholders:** Customers and Users|
| **Description:** If the user runs into any problem or just needs help with anything administrative related, they can submit a form to contact us, and we will respond with them as soon as possible. The form will ask for a name, email, and their question. If in any case, the form doesn’t go through then we will have our email on the website, and they can contact us that way. |
| **Origin:** Based on the project’s features, team members came up with the description during the first meeting |
| **Version:** 1.0  |
|**Date:** 1/31/2023
|  **Priority:** 7 |

**Comment by joerossi215** [comment]
completed
