### ISSUE TITLE
FR8. Delete Post 

### ISSUE THREAD

**Issue by yellow-tulips** [WSU-4110/mental-health-helper#16]
|FR8. Delete Post  |
|---|
|**Goal**: The user will be able to delete their post in the interaction page.
**Stakeholders:** Customers and Users|
| **Description:** If the user wants to delete their post or comment, there will be an option for them to do that. They will not be able to bring it back if they want to. They would have to make a new post. |
| **Origin:** Based on the project’s features, team members came up with the description during the first meeting |
| **Version:** 1.0  |
|**Date:** 1/31/2023
|  **Priority:** 8 |

**Comment by joerossi215** [comment]
completed
