### ISSUE TITLE
FR9. Edit Post  

### ISSUE THREAD

**Issue by yellow-tulips** [WSU-4110/mental-health-helper#17]
|FR9. Edit Post    |
|---|
|**Goal**: The user will be able to edit their post in the interaction page 
**Stakeholders:** Customers and Users|
| **Description:** After the user has posted or commented on a post, there will be a pen shaped button that will let them edit their post just in case there are spelling errors, or if they want to change up their words. It can be at any time and any day. |
| **Origin:** Based on the project’s features, team members came up with the description during the first meeting |
| **Version:** 1.0  |
|**Date:** 1/31/2023
|  **Priority:** 9 |

**Comment by joerossi215** [comment]
completed
