### ISSUE TITLE
FR12. Account Removal 

### ISSUE THREAD

**Issue by yellow-tulips** [WSU-4110/mental-health-helper#19]
| FR12. Account Removal  |
|---|
|**Goal**: The user will be allowed to delete their account at anytime.
**Stakeholders:** Customers and Users|
| **Description:** If at any point, the user doesn’t want to use their account anymore and want it removed, they can delete it from the system. The user can click on the gear icon in the upper right and from there will be able to delete their account. |
| **Origin:** It was decided during our first meeting on January 30th, 2023. |
| **Version:** 1.0  |
|**Date:** 1/31/2023
|  **Priority:** 12 |

**Comment by joerossi215** [comment]
completed
