### ISSUE TITLE
FR6. Take Mood Quiz

### ISSUE THREAD

**Issue by yellow-tulips** [WSU-4110/mental-health-helper#2]
|FR6. Take Mood Quiz|
|---|
|**Goal**: The user should be able to submit answers to the quiz’s questions to in return, receive feedback on how they might be feeling.
**Stakeholders:** Customers and Users|
| **Description:** There will also be a quiz located on the home page. This quiz lets the user answer 5 questions to get a better understanding of how they are feeling today. The result will show at the end, depicting a mood or emotion that best relates to the answers the user provided.|
| **Origin:** Team members decided on this during the first meeting, when first discussing the project.|
| **Version:** 1.0  |
|**Date:** 1/30/2023
|  **Priority:** 6 |

**Comment by joerossi215** [comment]
Completed
