### ISSUE TITLE
FR13. Add to Focus List

### ISSUE THREAD

**Issue by yellow-tulips** [WSU-4110/mental-health-helper#20]
|FR13. Add to Focus List|
|---|
|**Goal**: The user will be greeted with a message and a quote of the day when they open the website.
**Stakeholders:** Customers and Users|
| **Description:** The Stay Calm Focus List will provide a space for users to quickly note anything they need to remember to do. It will have a simple design since the main priority of our website is not productivity-focused. The focus list will be a way for users to lessen the burden of stress and distraction for users, especially those with ADHD. Users will be able to click on the “+” button, from where they can start typing to add a new task or idea to their list.|
| **Origin:** Team members decided on this during the first meeting, when first discussing the project.|
| **Version:** 1.0  |
|**Date:** 1/30/2023
|  **Priority:** 13 |

**Comment by joerossi215** [comment]
completed
