### ISSUE TITLE
FR14. Delete from Focus List

### ISSUE THREAD

**Issue by yellow-tulips** [WSU-4110/mental-health-helper#21]
|FR14. Delete from Focus List|
|---|
|**Goal**: The user can delete any tasks from their focus list.
**Stakeholders:** Customers and Users|
| **Description:** The Focus List also has a delete option that will be easy to use. The user may click on the trashcan symbol and click on which bullet point they want to delete. Then, that point will disappear from the list.|
| **Origin:** Team members decided on this during the first meeting, when first discussing the project.|
| **Version:** 1.0  |
|**Date:** 1/30/2023
|  **Priority:** 14 |

**Comment by joerossi215** [comment]
completed
