### ISSUE TITLE
FR15. Edit Profile

### ISSUE THREAD

**Issue by yellow-tulips** [WSU-4110/mental-health-helper#22]
|FR15. Edit Profile|
|---|
|**Goal**: User will be able to edit their profile.
**Stakeholders:** Customers and Users|
| **Description:** In the homepage, the user can click their name and “Edit Profile” in the top right corner. To add information, press the button next to it, or tap edit to make changes. After they’re done making changes, they click save to finish.|
| **Origin:** Team members decided on this during the first meeting, when first discussing the project.
| **Version:** 1.0  |
|**Date:** 1/31/2023
|  **Priority:** 15 |

**Comment by joerossi215** [comment]
completed
