### ISSUE TITLE
FR10. User Greeting

### ISSUE THREAD

**Issue by yellow-tulips** [WSU-4110/mental-health-helper#3]
|FR10. User Greeting|
|---|
|**Goal**: The user will be greeted with a message and a quote of the day when they open the website.
**Stakeholders:** Customers and Users|
| **Description:** The top of the website will have a “Welcome” sign. To the bottom of it, there will be a random motivational quote to inspire the users to have a good day. There will also be a list of important helpline-related phone numbers next to the “Welcome” and quote box at the top of the website. These phone numbers will allow the customer to quickly call, in case of mental emergencies.|
| **Origin:** Team members decided on this during the first meeting, when first discussing the project.|
| **Version:** 1.0  |
|**Date:** 1/30/2023
|  **Priority:** 10 |

**Comment by joerossi215** [comment]
completed
