### ISSUE TITLE
NFR2. Security 

### ISSUE THREAD

**Issue by yellow-tulips** [WSU-4110/mental-health-helper#6]
|NFR2. Security|
|---|
|**Goal**: The system will keep user information private.
**Stakeholders:** Customers and Users|
| **Description:** The system will not disclose any of the user’s personal information to any third-party source. The user can feel safe entering personal information when using the site’s different features. The user’s password must include at least 1 capital letter, 1 lowercase letter, 1 number and 1 character. This prevents the user from having their information stolen. |
| **Origin:** The group has decided this during their first meeting on January 30th, 2023.|
| **Version:** 1.0  |
|**Date:** 1/31/2023
|  **Priority:** 2 |

**Comment by joerossi215** [comment]
website keeps user information safe
