### ISSUE TITLE
NFR3. Compatibility

### ISSUE THREAD

**Issue by yellow-tulips** [WSU-4110/mental-health-helper#7]
|NFR3. Compatibility|
|---|
|**Goal**: The system will be compatible on all devices.
**Stakeholders:** Customers and Users|
| **Description:** The system will work on Windows, Mac, and include mobile devices like iOS and Android. Browsers including Edge, Chrome and Safari will also be supported. The user will have many options to help them get the help they need.  |
| **Origin:** The group has decided this during their first meeting on January 30th, 2023.|
| **Version:** 1.0  |
|**Date:** 1/31/2023
|  **Priority:** 3 |

**Comment by joerossi215** [comment]
completed
