### ISSUE TITLE
NFR4. Availability 

### ISSUE THREAD

**Issue by yellow-tulips** [WSU-4110/mental-health-helper#8]
|NFR4. Availability |
|---|
|**Goal**: The website will be available 24/7.
**Stakeholders:** Customers and Users|
| **Description:** Whenever the user is in need of some sort of mental help, the website would be available for them to use at any time. The user would be able to use all the features they need in order to better themselves. If in any case, the website is down we will send them a notification for when it is back up.  |
| **Origin:** Based on the project’s features, team members came up with the description during the first meeting |
| **Version:** 1.0  |
|**Date:** 1/31/2023
|  **Priority:** 4 |

**Comment by joerossi215** [comment]
website is always available
