### ISSUE TITLE
NFR5. Speed

### ISSUE THREAD

**Issue by yellow-tulips** [WSU-4110/mental-health-helper#9]
|NFR5. Speed |
|---|
|**Goal**: The website’s functions should be fast, loading within 2 seconds.
**Stakeholders:** Customers and Users|
| **Description:** When all users are online and have a strong internet connection, the website will be updated for them within 2 seconds. This is the pace at which a system must conduct editing to meet user expectations. Everyone should be able to finish their task quickly.  |
| **Origin:** Team members decided on this during the first meeting, when first discussing the project. |
| **Version:** 1.0  |
|**Date:** 1/31/2023
|  **Priority:** 5 |

**Comment by joerossi215** [comment]
website loads fast
